// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVnQ-6qoAlU6FRihQAqeDneFvivqmUboc',
    appId: '1:361752974328:web:4db00a214f5ae2b6cafc0d',
    messagingSenderId: '361752974328',
    projectId: 'ebic-2969c',
    authDomain: 'ebic-2969c.firebaseapp.com',
    storageBucket: 'ebic-2969c.firebasestorage.app',
    measurementId: 'G-MWMET5SPXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCVBoDJjHdO2EkOOyoXZ19ADRgYHh0-U8',
    appId: '1:361752974328:android:8ab016f2153e88c5cafc0d',
    messagingSenderId: '361752974328',
    projectId: 'ebic-2969c',
    storageBucket: 'ebic-2969c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRKswVfIkKLzFdlalQw7elBvN20Bs6sxo',
    appId: '1:361752974328:ios:9adf55ad7ad9fd47cafc0d',
    messagingSenderId: '361752974328',
    projectId: 'ebic-2969c',
    storageBucket: 'ebic-2969c.firebasestorage.app',
    iosBundleId: 'com.ebic.user.ebicUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRKswVfIkKLzFdlalQw7elBvN20Bs6sxo',
    appId: '1:361752974328:ios:9adf55ad7ad9fd47cafc0d',
    messagingSenderId: '361752974328',
    projectId: 'ebic-2969c',
    storageBucket: 'ebic-2969c.firebasestorage.app',
    iosBundleId: 'com.ebic.user.ebicUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVnQ-6qoAlU6FRihQAqeDneFvivqmUboc',
    appId: '1:361752974328:web:b7aacac9f6b4d2f2cafc0d',
    messagingSenderId: '361752974328',
    projectId: 'ebic-2969c',
    authDomain: 'ebic-2969c.firebaseapp.com',
    storageBucket: 'ebic-2969c.firebasestorage.app',
    measurementId: 'G-SMWJSYRZ6L',
  );
}
