import 'package:flutter/foundation.dart';
import '../../../core/api/api_client.dart';
import '../../../core/api/api_endpoints.dart';
import '../../../shared/models/health_pass_model.dart';

class HealthPassRepository {
  final ApiClient _api;

  HealthPassRepository({ApiClient? api}) : _api = api ?? ApiClient();

  /// Section 34 — Load available plans authoritatively from backend
  Future<List<HealthPassPlanModel>> fetchPlans() async {
    final res = await _api.get<List<dynamic>>(ApiEndpoints.healthPassPlans);
    if (res.success && res.data != null) {
      return res.data!
          .map((item) => HealthPassPlanModel.fromJson(item as Map<String, dynamic>))
          .toList();
    }
    throw Exception(res.message ?? 'Failed to load Health Pass plans');
  }

  /// Load a single plan authoritatively by ID or code
  Future<HealthPassPlanModel> fetchPlanById(String idOrCode) async {
    final res = await _api.get<Map<String, dynamic>>(ApiEndpoints.healthPassPlanDetail(idOrCode));
    if (res.success && res.data != null) {
      return HealthPassPlanModel.fromJson(res.data!);
    }
    throw Exception(res.message ?? 'Failed to load plan details');
  }

  /// Section 35 — Dynamic Plan Comparison Matrix from backend configuration
  Future<HealthPassComparisonModel> fetchComparison() async {
    final res = await _api.get<Map<String, dynamic>>(ApiEndpoints.healthPassPlansComparison);
    if (res.success && res.data != null) {
      return HealthPassComparisonModel.fromJson(res.data!);
    }
    throw Exception(res.message ?? 'Failed to load plan comparison');
  }

  /// Section 33 & 45 — Current Active Pass with live entitlements and anniversary period
  Future<ActiveHealthPassModel?> fetchCurrentPass() async {
    final res = await _api.get<Map<String, dynamic>>(ApiEndpoints.healthPassCurrent);
    if (res.success && res.data != null) {
      return ActiveHealthPassModel.fromJson(res.data!);
    }
    return null;
  }

  /// Section 38 — Dynamic Quote generated by backend pricing engine
  Future<HealthPassQuoteModel> getQuote({
    required String planCode,
    required int durationMonths,
    required List<String> memberIds,
  }) async {
    final res = await _api.post<Map<String, dynamic>>(
      ApiEndpoints.healthPassQuote,
      body: {
        'planCode': planCode,
        'durationMonths': durationMonths,
        'memberIds': memberIds,
      },
    );
    if (res.success && res.data != null) {
      return HealthPassQuoteModel.fromJson(res.data!);
    }
    throw Exception(res.message ?? 'Failed to generate pricing quote');
  }

  /// Section 39 — Create Draft Purchase with Idempotency Key
  Future<Map<String, dynamic>> purchaseDraft({
    required String planCode,
    required int durationMonths,
    required List<String> memberIds,
    String? idempotencyKey,
  }) async {
    final key = idempotencyKey ?? 'hp_pur_${DateTime.now().millisecondsSinceEpoch}';
    final res = await _api.post<Map<String, dynamic>>(
      ApiEndpoints.healthPassPurchase,
      body: {
        'planCode': planCode,
        'durationMonths': durationMonths,
        'memberIds': memberIds,
      },
      requiresIdempotency: true,
      explicitIdempotencyKey: key,
    );
    if (res.success && res.data != null) {
      return res.data!;
    }
    throw Exception(res.message ?? 'Failed to create Health Pass order');
  }

  /// Section 40 — Initiate Payment
  Future<Map<String, dynamic>> initiatePayment({
    required String healthPassId,
    required String method,
    required String idempotencyKey,
  }) async {
    final res = await _api.post<Map<String, dynamic>>(
      ApiEndpoints.healthPassPayInitiate(healthPassId),
      body: {
        'method': method,
      },
      requiresIdempotency: true,
      explicitIdempotencyKey: idempotencyKey,
    );
    if (res.success && res.data != null) {
      return res.data!;
    }
    throw Exception(res.message ?? 'Failed to initiate payment');
  }

  static final ValueNotifier<int> passUpdateNotifier = ValueNotifier<int>(0);

  static void notifyPassUpdated() {
    passUpdateNotifier.value++;
  }

  /// Section 40 — Verify Payment & Trigger Activation
  Future<Map<String, dynamic>> verifyPayment({
    required String healthPassId,
    required String gatewayPaymentId,
    required String gatewaySignature,
    required String idempotencyKey,
  }) async {
    final res = await _api.post<Map<String, dynamic>>(
      ApiEndpoints.healthPassPayVerify(healthPassId),
      body: {
        'gatewayPaymentId': gatewayPaymentId,
        'gatewaySignature': gatewaySignature,
      },
      requiresIdempotency: true,
      explicitIdempotencyKey: idempotencyKey,
    );
    if (res.success && res.data != null) {
      notifyPassUpdated();
      return res.data!;
    }
    throw Exception(res.message ?? 'Failed to verify payment');
  }

  /// Section 43 & 44 — Entitlements & Immutable Usage Ledger
  Future<HealthPassUsageLedgerModel> fetchUsage(String healthPassId) async {
    final res = await _api.get<Map<String, dynamic>>(ApiEndpoints.healthPassUsage(healthPassId));
    if (res.success && res.data != null) {
      return HealthPassUsageLedgerModel.fromJson(res.data!);
    }
    throw Exception(res.message ?? 'Failed to load entitlement usage ledger');
  }

  /// Section 48 — Subscriptions and purchases history
  Future<List<HealthPassHistoryItemModel>> fetchHistory() async {
    final res = await _api.get<List<dynamic>>(ApiEndpoints.healthPassHistory);
    if (res.success && res.data != null) {
      return res.data!
          .map((item) => HealthPassHistoryItemModel.fromJson(item as Map<String, dynamic>))
          .toList();
    }
    return [];
  }

  /// Section 47 — Renewal Quote
  Future<HealthPassQuoteModel> quoteRenewal({
    required String healthPassId,
    required String planCode,
    required int durationMonths,
    required List<String> memberIds,
  }) async {
    final res = await _api.post<Map<String, dynamic>>(
      ApiEndpoints.healthPassRenewQuote(healthPassId),
      body: {
        'planCode': planCode,
        'durationMonths': durationMonths,
        'memberIds': memberIds,
      },
    );
    if (res.success && res.data != null) {
      return HealthPassQuoteModel.fromJson(res.data!);
    }
    throw Exception(res.message ?? 'Failed to calculate renewal quote');
  }

  /// Section 47 — Create Renewal Draft
  Future<Map<String, dynamic>> createRenewal({
    required String healthPassId,
    required String planCode,
    required int durationMonths,
    required List<String> memberIds,
    String? idempotencyKey,
  }) async {
    final key = idempotencyKey ?? 'hp_ren_${DateTime.now().millisecondsSinceEpoch}';
    final res = await _api.post<Map<String, dynamic>>(
      ApiEndpoints.healthPassRenew(healthPassId),
      body: {
        'planCode': planCode,
        'durationMonths': durationMonths,
        'memberIds': memberIds,
      },
      requiresIdempotency: true,
      explicitIdempotencyKey: key,
    );
    if (res.success && res.data != null) {
      return res.data!;
    }
    throw Exception(res.message ?? 'Failed to create renewal order');
  }

  /// Apply Coupon
  Future<Map<String, dynamic>> applyCoupon(String healthPassId, String code) async {
    final res = await _api.post<Map<String, dynamic>>(
      '/health-pass/$healthPassId/coupon',
      body: {'code': code},
    );
    if (res.success && res.data != null) {
      return res.data!;
    }
    throw Exception(res.message ?? 'Invalid coupon code');
  }

  /// Remove Coupon
  Future<void> removeCoupon(String healthPassId) async {
    await _api.delete('/health-pass/$healthPassId/coupon');
  }
}
